version: "3"
services:

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - socialnetwork
      - frontend
    ports:
      - 80:80
    networks:
      - socialnetwork

  frontend:
    image: docker.pkg.github.com/kirillamurskiy/otus-highload-2019-09/frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - 5020:3000
    networks:
      - socialnetwork

  socialnetwork:
    image: docker.pkg.github.com/kirillamurskiy/otus-highload-2019-09/socialnetwork:latest
    container_name: socialnetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Auth__UseTestAuth=false
      - ConnectionStrings__SocialNetworkDb=server=${SocialNetworkServer};port=${SocialNetworkPort};database=${SocialNetworkDb};user=${SocialNetworkUser};password=${SocialNetworkUserPassword};
    restart: unless-stopped
    ports:
      - 5011:80
    depends_on:
      - socialnetwork_db_migrator
    networks:
      - socialnetwork

  socialnetwork_db_migrator:
    image: docker.pkg.github.com/kirillamurskiy/otus-highload-2019-09/socialnetwork-db-migrator:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SocialNetwork__Server=${SocialNetworkServer}
      - SocialNetwork__Port=${SocialNetworkPort}
      - SocialNetwork__Creator=${SocialNetworkCreator}
      - SocialNetwork__CreatorPassword=${SocialNetworkCreatorPassword}
      - SocialNetwork__CreatorDb=${SocialNetworkCreatorDb}
      - SocialNetwork__Migrator=${SocialNetworkMigrator}
      - SocialNetwork__MigratorPassword=${SocialNetworkMigratorPassword}
      - SocialNetwork__MigratorDb=${SocialNetworkDb}
      - SocialNetwork__CreateDb=true
      - SocialNetwork__ShowPII=true
    networks:
      - socialnetwork
  
networks:
  socialnetwork:
    driver: bridge